apiVersion: apps/v1
kind: Deployment
metadata:
  name: abstergo-website-deployment
  labels:
    app: abstergo-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abstergo-website
  template:
    metadata:
      labels:
        app: abstergo-website
    spec:
      containers:
        - name: abstergo-website
          image: hardikgangwar/abstergo-website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
