apiVersion: v1
kind: Service
metadata:
  name: abstergo-website-service
  labels:
    app: abstergo-website
spec:
  type: NodePort
  selector:
    app: abstergo-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
